image: ghcr.io/cirruslabs/android-sdk:34

stages:
  - checks

cache:
  key: "$CI_PROJECT_ID"
  paths:
    - .gradle/
    - ~/.gradle/

# DETEKT
detekt:
  stage: checks
  script:
    - ./gradlew detekt
  artifacts:
    when: always
    paths:
      - build/reports/detekt/

# TESTS
tests:
  stage: checks
  script:
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - build/test-results/
      - build/reports/tests/
